server.port=8080

#Sping Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d6qfa6n5r7bs738g4org-a:5432/platzi_play_db_rf18
spring.datasource.username=asael
spring.datasource.password=RMp2Znr21iW5970lX9zyxymkCei1ogJx

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

#LangChain4j
langchain4j.open-ai.chat-model.api-key=demo